---
- hosts: localhost
  gather_facts: no
  tasks:
    # Check the jumphost credentials
    - set_fact:
        jh_ssh_private_key: "{{ lookup('env','JH_SSH_PRIVATE_KEY') }}"
    - debug:
        msg: "{{ jh_ssh_user }} {{ jh_ssh_private_key }}"
    - debug:
        msg: "{{ hostvars['127.0.0.1']['jh_ssh_user'] }} {{ hostvars['127.0.0.1']['jh_ssh_private_key'] }}"
    - name: Run the hostname command on Jumphost
      shell:
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {{ hostvars['127.0.0.1']['jh_ssh_private_key'] }} {{ jh_ssh_user }}@{{ jh_ip }} hostname

